#!/bin/bash
#set -x
FIND=`ps aux | gawk '{print $2" "$11}' | grep '.skew'`
if [ "$FIND" == "" ]; then
  echo skew process not found
  exit
fi
PID=`ps aux | gawk '{print $2" "$11}' | grep '.skew' | gawk '{print $1}'`
echo Killing...
ps aux | grep $PID | grep 'skew'
kill $PID
exit

