#!/bin/bash
# Calculate and report skew estimates based on
# previous day's RBN data

# Move to correct folder to allow cron execution on RPi
[ -d "/home/pi/skewsrv" ] && cd /home/pi/skewsrv

FOLDER="rbndata"
DATE=`date -u --date="1 days ago" +%Y%m%d`
OLDDATE=`date -u --date="10 days ago" +%Y%m%d`
REFFILE="reference"
CSVFILE=$FOLDER/rbndata.csv
ZIPFILE=$FOLDER/rbndata.zip
TOKEN=$FOLDER/dataupdated

[ -d $FOLDER ] || mkdir $FOLDER

echo "Job started "`date -u "+%F %T" `
START=$SECONDS

# Do the work

# Uncomment line to always download
#echo "Never" > $TOKEN

# Check if we already did the work for
# today, if so, exit
[ -f $TOKEN ] || echo "Never" > $TOKEN

if [ "$DATE" != "`cat $TOKEN`" ]; then
    echo "Downloading RBN data for "`date -u --date="1 days ago" +%Y-%m-%d`
    wget --quiet --no-hsts http://www.reversebeacon.net/raw_data/dl.php?f=$DATE -O $ZIPFILE

    FILESIZE=$(stat -c%s $ZIPFILE)
    if [[ $FILESIZE != "0" ]]; then
        gunzip < $ZIPFILE > $CSVFILE
        echo "Downloaded yesterday's "$((`wc -l < $CSVFILE` - 2))" spots into $CSVFILE"
        echo $DATE > $TOKEN
    else
        echo "Could not download yesterday's RBN data!"
        echo "Job failed "`date -u "+%F %T" `
        exit
    fi
fi

# Do the work

printf "Selecting list of reference skimmers...\n"

./skewday -f $CSVFILE

echo "Job done "`date -u "+%F %T" `

exit
